# Generated by Django 3.1.3 on 2020-12-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaskData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_child', models.IntegerField(blank=True, null=True)),
                ('num_adult', models.IntegerField(blank=True, null=True)),
                ('agency_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_code', models.CharField(blank=True, max_length=100, null=True)),
                ('agency_address', models.CharField(blank=True, max_length=100, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, choices=[('臺北市', '臺北市'), ('新北市', '新北市'), ('桃園市', '桃園市'), ('臺中市', '臺中市'), ('臺南市', '臺南市'), ('高雄市', '高雄市'), ('基隆市', '基隆市'), ('新竹市', '新竹市'), ('嘉義市', '嘉義市'), ('新竹縣', '新竹縣'), ('苗栗縣', '苗栗縣'), ('彰化縣', '彰化縣'), ('南投縣', '南投縣'), ('雲林市', '雲林市'), ('嘉義縣', '嘉義縣'), ('屏東縣', '屏東縣'), ('宜蘭縣', '宜蘭縣'), ('花蓮縣', '花蓮縣'), ('臺東縣', '臺東縣'), ('澎湖縣', '澎湖縣'), ('連江縣', '連江縣'), ('金門縣', '金門縣')], max_length=100, null=True)),
            ],
            options={
                'db_table': 'mask_data',
                'managed': True,
            },
        ),
    ]
