# Generated by Django 3.1.3 on 2020-12-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maskdata',
            options={'managed': False},
        ),
    ]
